### ISSUE TITLE
Question about merged cells

### ISSUE THREAD

**Issue by jmarca** [Tux/Spreadsheet-Read#1]
This is either a feature request or a how to question.

I want to used "merged" but I'm not sure there is a non-ambiguous way to use it.

Example

```
    A      B     C     D     E
 +------+-----------+-----+-----+
1|      |   notes   |     |     |
 +------+           +-----+-----+
2|  mon |           |     |     |
 |      +-----+-----+-----+-----+
3|      | ext | int |     |     |
 +------+-----+-----+-----+-----+
4|      |     |     |     |     |
 +------+-----+-----+-----+-----+

```

In the above case, the "id" column is merged, but vertically, and the "notes" cells are merged H and V.  I'm parsing generic spreadsheets that do not follow exact patterns month to month (yay users) but they have the same content.  I wanted to try to use the "merged" attribute to test what columns the non-null value is relevant for.  In the above case, "mon" is merged, but merged down, and "notes" is merged right and down (yes, I have that case in practice).  If I'm working on "mon" and I test the cell to the right for null or empty as well as merged, this would falsely indicate that the "mon" cell is merged right.

Put another way, to the _eye_, it is clear that A3 is merged to the parent cell A2, and that all of [B2,C1,C2] are merged to the parent cell B1.  But as far as I can tell, there is no unambiguous way using the "attr" parameters of Spreadsheet::Read to identify the "parent" of a merged, empty cell, right?

Perhaps this is a question for Spreadsheet::ParseExcel or Spreadsheet::ParseXLSX?

**Comment by Tux** [comment]
You are right.

As there was no way to identify merged cells by the time of writing, and I wanted to present a unified interface to all supported spreadsheets, I never put time in the analysis of how merged cells are returned by the underlying parser other than returning the info as-is.

CSV does not support merged cells (though that may change in the future with support for CSV for the web).

Neither Spreadsheet::ParseExcel nor Spreadsheet::XLSX mention anything about merged cells or a property that can be set or asked for to test for it. That the underlying parser does not return information about merged cells, implicates that Spreadsheet::Read does not have that information available. The fact that information about merged cells is available but undocumented makes it unreliable as it may change without notice.

Spreadsheet::ReadSXC does support merged cells, but the rest of that module shows its age, so converting XLS or XLSX to SXC just to deal with merged cells is not really an option. (Somebody should write a reliable Spreadsheet::ParseODS based on the UI of Spreadsheet::ParseExcel and Spreadsheet::ParseXLSX).

Conclusion: yes, ask in the ParseExcel and/or ParseXLSX queue how they see support for merged cells (other than the undocumented "merge" attribute per cell). If they have a reliable interface, I could try to make that visible in Spreadsheet::Read beyond the current implementation. Their API should e.g. also note thetop-left cell the merged cell belongs to, otherwise, you cannot say if B2 is merged if it is merged with A2 or with B1.

For now, I'll make a note in the documentation.

**Comment by Tux** [comment]
FWIW there is an _undocumented_ attribute in Spreadsheet::ParseExcel that I blindly copy into the cell attributes: it is called "merged" and documented as such. If you enable "attr", you'll see the "merged" indicator in the attr information

<pre>use Spreadsheet::Read;
my $ss = ReadData ("merged.xlsx", attr => 1)->[1];
foreach my $row (1 .. $ss->{maxrow}) {
    foreach my $col (1 .. $ss->{maxcol}) {
        my $cell = cr2cell ($col, $row);
        printf "%s %-6s %d  ", $cell, $ss->{$cell},
            $ss->{attr}[$col][$row]{merged};
        }
    print "\n";
    }
=>
A1        0  B1 notes  1  C1        1
A2 mon    1  B2        1  C2        1
A3        1  B3 ext    0  C3 int    0</pre>

I don't see the information on to what field it is merged, just that it _is_ merged.

**Comment by Tux** [comment]
Can you checkout https://github.com/Tux/Spreadsheet-Read/commit/5b54bc06a61dac94771c5911f90b55ce5feec646 and see if this meets your needs?

I requested documentation (as an issue) in the repositories of Spreadsheet::ParseExcel and Spreadsheet::ParseXLSX.

**Comment by jmarca** [comment]
Wow! I will try it out today and report back.

**Comment by Tux** [comment]
@jmarca and? Does it?

**Comment by jmarca** [comment]
On Fri, Mar 06, 2015 at 02:55:26AM -0800, H.Merijn Brand wrote:

> @jmarca and? Does it?

Bleh! Sorry.  It's that "work intervenes" thing.

I will test it ~~this evening~~ tomorrow, and file a documentation request with the
upstream projects too.

(Update...work intervened some more)

**Comment by Tux** [comment]
Implemented and solved. Closing
