### ISSUE TITLE
Provide option to install examples with a name prefix

### ISSUE THREAD

**Issue by StefanBruens** [Tux/Spreadsheet-Read#18]
Two of the examples clash with files provided by other software:
- ssdiff is a tool also provided by gnumeric
- xls2csv conflicts with http://search.cpan.org/~ken/xls2csv/script/xls2csv

**Comment by Tux** [comment]
Regarding xls2csv
• https://metacpan.org/author/KEN does not mention xls2csv
• https://metacpan.org/author/KEN/releases shows xls2csv as script as of 24 Sep 2005
• Mine exists in the examples since 14 Jun 2005, so I should not care (KEN could, though I doubt he will)
• I'm not going to rename it. I added a note in the README regarding this possible clash
• Installing is optional (though on by default as most of my users want it)

Regarding ssdiff
• I didn't know
• I see https://www.mankier.com/1/ssdiff shows the functionality is similar
• I'll contemplate on making it support the same options
• I'm not going to rename it. I added a note in the README regarding this possible clash
• Installing is optional (though on by default as some of my users want it)
