### ISSUE TITLE
Companion module: Spreadsheet::Read::Ingester

### ISSUE THREAD

**Issue by sdondley** [Tux/Spreadsheet-Read#24]
I wrote a wrapper for Spreadsheet::Read to help speed repeated parsing of the same file.

[Details here.](https://metacpan.org/pod/release/STEVIED/Spreadsheet-Read-Ingester-0.010/lib/Spreadsheet/Read/Ingester.pm)

Feedback appreciated. Hopefully it's of some use to others.

**Comment by Tux** [comment]
If it helps you, use it. I see value for it, though for me it probably won't help: If I need to reparse data often, I convert it to CSV. Nothing is as easy to port to other machines (and other architectures) as CSV, and - using Text::CSV_XS - it is trailblazing fast compared to all the other spreadsheets.
@sdondley I'd suggest to use Sereal instead of Storable. Not only for speed. Or at least have an option to choose.

**Comment by sdondley** [comment]
OK, good to know. Thanks for the suggestions. I will be dealing with converting from Excel directly so it's probably a lot more useful for that.

**Comment by sdondley** [comment]
I think what I'll do is add an option to save as a csv file as well as a pure data structure.

**Comment by Tux** [comment]
Spreadsheet::Read comes with xlsx2csv, so feel free to steal from it :)
As you can imagine xlsx2csv uses Spreadsheet::Read to read the sheet*s* and Text::CSV_XS to write CSV, so all supportes spreadsheets can be turned into CSV
As I wrote my first reply, I realized supporting Sereal was on my TODO for Tie::Hash::DBD, so I just did it. See https://github.com/Tux/Tie-Hash-DBD/commit/a3b1d525d74a1d78677514bbff11c41e7ace2a75 for how transparently that can be done.
And I 100% agree that re-opening xlsx files with big datasets is a real PITA

**Comment by sdondley** [comment]
Thanks, yeah, was just in the middle of researching xls2csv tool as a possible way to implement it. And thanks for the tip on implementing Sereal.

**Comment by Tux** [comment]
Closing this issue, as there are no open issues for Spreadsheet::Read
