### ISSUE TITLE
access same content via merged cells

### ISSUE THREAD

**Issue by torbjorn** [Tux/Spreadsheet-Read#25]
Hi, would it be possible to link to the same content from merged cells? Essentially how ever I choose to access content, if I ask for a cell from a merged range, I'd get the content from the cell that defines the content of that range?

**Comment by Tux** [comment]
Start reading https://metacpan.org/pod/Spreadsheet::Read#Merged-cells

You mean that asking for the formatted value of `B1`, `C1`, `B2`, and `C2` will all return the same value (of B1)?

If that would be (the) default behavior, then it might cause a increase of content on sheets with a lot of merged cells, as it needs to copy (or alias) that data for each merged cell in the range except for the base cell. And what happens if the content of `B2` is changed or the attributes of `C1`? Should it change the content/attribute of all the cells?

**Comment by torbjorn** [comment]
I see,

Problem is perhaps that I'm working with rows where some cells are vertically merged. Are you saying that i should still see merged content in any cell from a merged range?

**Comment by Tux** [comment]
ATM you should not: only the first (top-left) cell in a merged range will show the content. This is all due to how the underlying parser returns the data. Spreadsheet::Read just returns the data in a uniform interface, added with some generic API. The docs from the parsers on how they deal with merged celss is somewhat obfuscated if present at all.

**Comment by Tux** [comment]
I close this issue, as it it very well decribed now how Spreadsheet::Read behaves with merged cells.

I have added an option (`merge => 1`) that will copy all data of the top-left cell in a merged area to all other cells in that area.
This will be available in the upcoming 0.82 release
