### ISSUE TITLE
failed to read cells with multiline edited by libreoffice 

### ISSUE THREAD

**Issue by lordmfia** [Tux/Spreadsheet-Read#34]
Hi i use the following code to read excel sheet [test_multi_line.xlsx](https://github.com/Tux/Spreadsheet-Read/files/5501179/test_multi_line.xlsx)
`       my $book  = ReadData ("test_multi_line.xlsx");`
`        unless($book){  die "couldn't open Excel sheet \n";     }`
`        my $tmp_str = $book->[1]{cell}[1][1] ;`
`        my @tmp_arr = split /^/ , $tmp_str ;`
`        print "$tmp_str" ;`
`        my $arr_length = @tmp_arr;`
`        if ($arr_length > 1 ) {print "PASSED\n";}`
`        else { die ("\x1b[33;41;1mFAILED\x1b[0m\n please use sim-4 or maxl05\n");} ` 

i tried it on 2 versions of READ 
V0.75 : works correctlly 
V0.82 : Failed

**Comment by Tux** [comment]
I am convinced it is the backend parser you are using:
``` perl
#!/pro/bin/perl

use 5.14.2;
use warnings;

use Spreadsheet::Read;

my $book = ReadData ("issue34.xlsx") or die "couldn't open Excel sheet\n";
my $meta = $book->[0];
my $data = $book->[1];
say "Using Spreadsheet::Read-", Spreadsheet::Read->VERSION;
say "With $meta->{type} parser $meta->{parser}-$meta->{version}";
my $tmp_str = $data->{cell}[1][1];
my @tmp_arr = split m/^/ => $tmp_str;
say "'$tmp_str'";
@tmp_arr > 1
    ? say "PASSED"
    : die "FAILED\n please use sim-4 or maxl05\n";
```
```
$ perl issue34.pl
Using Spreadsheet::Read-0.83
With xlsx parser Spreadsheet::ParseXLSX-0.27
'1
2
3'
PASSED
```
Please verify that you are using Spreadsheet::ParseXLSX and not the buggy braindead unmaintained Spreadsheet::XLSX

**Comment by lordmfia** [comment]
Hi @Tux  , 

Many thanks for your reply 
i think you are correct it a problem with the parser 

i have checked both cases again and here are the results :

Using Spreadsheet::Read-0.81
With xlsx parser Spreadsheet::XLSX-0.15
'1&#10;2&#10;3'
FAILED

Using Spreadsheet::Read-0.75
With xlsx parser Spreadsheet::ParseXLSX-0.27
'1
2
3'
PASSED

So could you please help me on how to force ParseXLSX to be the parser in this script 

Thanks for your support 
Regards,

**Comment by Tux** [comment]
If both modules are installed, Spreadsheet::Read will use Spreadsheet::ParseXLSX, so you don't need to force anything in that direction. The [documentation](https://github.com/Tux/Spreadsheet-Read/blob/master/doc/Spreadsheet-Read.md#readdata) already tells you how to force parser selection:
--8<---
parser

Force the data to be parsed by a specific format. Possible values are csv, prl (or perl), sc (or squirrelcalc), sxc (or oo, ods, openoffice, libreoffice) xls (or excel), and xlsx (or excel2007).

When parsing streams, instead of files, it is highly recommended to pass this option.

Spreadsheet::Read supports several underlying parsers per spreadsheet type. It will try those from most favored to least favored. When you have a good reason to prefer a different parser, you can set that in environment variables. The other options then will not be tested for:

  env SPREADSHEET_READ_CSV=Text::CSV_PP ...
-->8---

**Comment by lordmfia** [comment]
Many thanks For the support @Tux 

Regards,
Gohar
